# SPDX-FileCopyrightText: 2021 Katie Mulliken <katie@mulliken.net>
#
# SPDX-License-Identifier: Apache-2.0

[tool.poetry]
name = "ha-wyzeapi"
version = "0.1.24"
description = "A Home Assistant integration for Wyze devices"
authors = ["Katie Mulliken <katie@mulliken.net>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.11.0,<3.13"
homeassistant = ">=2024"
wyzeapy = { git = "https://github.com/douglaslinsmeyer/wyzeapy.git", branch = "main" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
